### ISSUE TITLE
Rename package and repo to opbeans-node

### ISSUE THREAD

**Issue by watson** [elastic/opbeans-node#25]
Before performing the rename we need to make sure [apm-integration-testing](https://github.com/elastic/apm-integration-testing) doesn't depend on the old name.

**Comment by watson** [comment]
@graphaelli do you know if apm-integration-testing depends on the repo or package name being just "opbeans"?

**Comment by graphaelli** [comment]
I don't believe there is any dependency.  I'd vote go ahead and we'll quickly fix any issues if/when they arise.

**Comment by beniwohli** [comment]
We'll probably have to update the repo name for the automated docker hub build. Unless they pick up renames via API or something

**Comment by watson** [comment]
Thanks :) I'll try and see what happens

**Comment by watson** [comment]
Done. Docker Hub didn't pick it up unfortunately

@beniwohli I can't find anywhere to change the repo inside of Docker Hub? Maybe it's a permissions issue?

**Comment by beniwohli** [comment]
@watson looks like you can't change it on Docker Hub, but I was able to change it in Docker Cloud ( ¯\_(ツ)_/¯ ) following these instructions https://github.com/docker/hub-feedback/issues/313#issuecomment-265843090

**Comment by beniwohli** [comment]
Hmm, turns out automated builds on Docker Cloud don't seem to support repository links (confusing name, this feature is about linking Docker repositories, not github repos, and it allows us to trigger re-builds of the backend images if the frontend image changes). I sent a support request to Docker to ask if the feature is available on Docker Cloud, but I don't think it is. If all else fails, we can simply recreate the build on Docker Hub with the new repo name

**Comment by watson** [comment]
@beniwohli any update on this from Docker Hub?

**Comment by beniwohli** [comment]
@watson unfortunately not. It seems Docker decided the best course of action with my support request was to ignore it ¯\_(ツ)_/¯ 

I guess the best solution is to delete the repo in Docker Hub / Docker Cloud and create a new one in Docker Hub. Should I do that?

**Comment by watson** [comment]
If you think that's easiest 👍 I don't know the pro's/con's

**Comment by watson** [comment]
awesome, thanks 👍
