### ISSUE TITLE
"Integration Tests" check on master branch is never reported to GitHub

### ISSUE THREAD

**Issue by trentm** [elastic/opbeans-node#81]
For some reason the "Integration tests" check on commits to master is never reported:
https://github.com/elastic/opbeans-node/commits/master

For example for this commit: https://github.com/elastic/opbeans-node/commit/3d14e4774452cf732bcd0023b329ce17863aa2fd
The "pending" "Integration Tests" check links to https://apm-ci.elastic.co/job/apm-integration-tests-selector-mbp/job/master/ which doesn't indicate which build it was. Clicking around, that opbeans-node commit's build trigger this integration test build: https://apm-ci.elastic.co/job/apm-integration-tests-selector-mbp/job/master/15957/
That completed, but the check on the opbeans-node commit has not been updated.

Note that I believe Integration Tests checks *are* being updated for PRs, e.g. this one: https://github.com/elastic/opbeans-node/pull/78

Is someone in @elastic/observablt-robots able to help track down why?

**Comment by v1v** [comment]
I'm working on it

**Comment by v1v** [comment]
As far as I see the parameters are passed correctly:

- https://apm-ci.elastic.co/job/apm-integration-tests-selector-mbp/job/master/15957/parameters/
![image](https://user-images.githubusercontent.com/2871786/114534686-2b6b5e80-9c47-11eb-8155-59f0d0e2019c.png)

And the `githubNotify` step is called:

![image](https://user-images.githubusercontent.com/2871786/114534867-5b1a6680-9c47-11eb-9f7a-88779424b5a9.png)

I was somehow thinking the parameters between the obeans-node pipeline and the test-selector pipeline were the root issue, but as far as I see all of the are correct.

I'll keep debugging

**Comment by v1v** [comment]
I'm a bit confused now :/ since my PR with some verbose traces somehow worked like a charm.

What did I do?

1) Raised https://github.com/elastic/apm-integration-testing/pull/1108
2) Triggered https://apm-ci.elastic.co/job/apm-integration-tests-selector-mbp/view/change-requests/job/PR-1108/2/parameters/ with the same parameters that the one used in the master branch -> https://apm-ci.elastic.co/job/apm-integration-tests-selector-mbp/job/master/15957/parameters/
3) Log traced mentioned `[INFO] githubCheckNotify: Integration Tests=SUCCESS for elastic/opbeans-node.git@3d14e4774452cf732bcd0023b329ce17863aa2fd`


And the GitHub commit status check is not anymore waiting for -> 
![image](https://user-images.githubusercontent.com/2871786/114547825-d8010c80-9c56-11eb-8088-7faed27dbf39.png)

That points to -> https://apm-ci.elastic.co/job/apm-integration-tests-selector-mbp/job/PR-1108/2/display/redirect

I'll rebuild the original build -> https://apm-ci.elastic.co/job/apm-integration-tests-selector-mbp/job/master/15957 and see if the GitHub commit status check gets updated

**Comment by v1v** [comment]
https://apm-ci.elastic.co/blue/organizations/jenkins/apm-integration-tests-selector-mbp/detail/master/16009/pipeline worked and notified the status 

I wonder if the issue was somehow with the GitHub itself though I don't see any incidences in the service:
- https://www.githubstatus.com/history


I'm running a whole new build -> https://apm-ci.elastic.co/job/apm-agent-nodejs/job/opbeans-node-mbp/job/master/74/


Let's see how it goes

**Comment by trentm** [comment]
I doubt it is GitHub, given this is happening reliably. It also didn't update the check status for this commit yesterday: https://github.com/elastic/opbeans-node/commit/b0622ef5f8e10e768abd8e9256592e22e549fbe5

**Comment by trentm** [comment]
This is still happening. All master commits show checks are incomplete: 
![Screen Shot 2021-04-26 at 9 27 13 AM](https://user-images.githubusercontent.com/46866/116117958-af730c80-a671-11eb-87d7-7c10f621020a.png)

This isn't blocking any work however.

**Comment by trentm** [comment]
This is obsolete now. We no longer have an "Integration Tests" check/action.
